import BalanceGraph from "../components/metrics/BalanceGraph";
import CurrencyDropdown from "../components/metrics/CurrencyDropdown";
import SavingsTracker from "../components/metrics/SavingsTracker";
import TransactionLog from "../components/transactions/TransactionLog";
import AddTransactionButton from "../components/transactions/AddTransactionButton";
import DeleteTransactionButton from "../components/transactions/DeleteTransactionButton";
import UpdateSavingGoalButton from "../components/metrics/UpdateSavingGoalButton";
import LogOutButton from "../components/login_and_signup/LogOutButton";
import DefaultHeader from "../components/default/DefaultHeader";

import FintrackLogo from "../assets/images/FintrackLogo.png";
import FinancialMetrics from "../components/metrics/FinancialMetrics";

import "../assets/css/dashboard.css";
import LuckyAdviser from "../components/gemini/LuckyAdviser";

/*
 * When adding your new component:
 * remove the p tags and replace them with your respective react components, and remove the bg-[colour] property in its wrapped <div>
 *
 * The bg-[colour] properties have been added to help visualise where each component should go.
 */

export default function Dashboard() {
    return (
        <>
            <div className="topBar">
                <div className="logoContainer">
                    <img src={FintrackLogo} alt="logo"></img>
                </div>
                <SavingsTracker />
                <LogOutButton />
            </div>
            <div className="scrollableContent">
                <h1 className="genericH1">Welcome to FinTrack!</h1>
                <h2 className="genericH2">
                    FinTrack is a free, open source financial tracker designed
                    and developed for SOFTENG 310, software evolution and
                    maintenance, at The University of Auckland, New Zealand. The
                    project is a joint effort between{" "}
                    <a
                        style={{ color: "var(--color3)" }}
                        href="https://github.com/Taks0708"
                    >
                        Meow Meow Silly Cats
                    </a>{" "}
                    and{" "}
                    <a
                        style={{ color: "var(--color3)" }}
                        href="https://https://github.com/SE310-Team-1.com/Taks0708"
                    >
                        Group 1
                    </a>
                    (We didn't need a name, our designation in first place
                    speaks volumes).
                </h2>
                <h1 className="genericH1">Get stuck in</h1>
                <h2 className="genericH2">
                    This app supports a suite of features designed to help you
                    track your financial progress towards a set goal. To get
                    started, use the <b>Update Savings Goal</b> button in the{" "}
                    <b>side-bar</b> to the right. To record a new financial
                    transaction to or from your savings, use the{" "}
                    <b>Add Transaction</b> button. Once a transaction has been
                    created, it can be viewed in the <b>Transaction History</b>{" "}
                    table below. You can search these entries by date, update,
                    and delete them. This app supports app-wide currency
                    conversion. This can be accessed via the{" "}
                    <b>currency dropdown</b> on the right, along with a summary
                    of your finances. For further financial advice, consult our{" "}
                    <a
                        style={{ color: "var(--color3)" }}
                        href="https://gemini.google.com/"
                    >
                        Gemini-AI
                    </a>{" "}
                    powered finance advisor at the bottom of the page.
                </h2>
                <DefaultHeader>
                    ---- ---- Balance Over Time ---- ----
                </DefaultHeader>
                <BalanceGraph />
                <FinancialMetrics />
                <DefaultHeader>
                    ---- ---- Transaction History ---- ----
                </DefaultHeader>
                <TransactionLog />
                <DefaultHeader>
                    ---- ---- AI Powered Finance Advice ---- ----
                </DefaultHeader>
                <h2 className="genericH2">
                    <b>DISCLAIMER:</b> While Gemini is particuarly good at
                    summarising finance concepts, advice generated by this
                    website may occasionally be inacurate or misleading due to
                    the nature of machine learning. Please validate advice with
                    a reliable source before acting on it.
                </h2>
                <LuckyAdviser />
            </div>
            <div className="sideBar">
                <AddTransactionButton />
                <DeleteTransactionButton />
                <UpdateSavingGoalButton />
                <div
                    style={{ height: "40px", width: "100%", float: "left" }}
                />{" "}
                {/* Space between groups of buttons */}
                <CurrencyDropdown />
            </div>
        </>
    );
}
